blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/your-org/your-repo/blob/main/WORKFLOW.md
    about: Please check the workflow guide before filing an issue.
  - name: Discussions
    url: https://github.com/your-org/your-repo/discussions
    about: For questions, ideas, or general conversation, use Discussions instead.
