name: Validate Dictionaries

on:
  push:
    branches:
      - main
      - nouvo-ayiti-2075-blog
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run dictionary validation
        run: npm run check-dicts
